name: Test on Pull Request

on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: [KU]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clean up
        run: |
          docker image prune -a -f

      - name: Build Docker Container
        run: |
          docker build . -t test-admin-webpreview  # Build the Docker image with the tag 'admin-webpreview'

