name: Run Expo on Test Branch Update

on:
  push:
    branches:
      - main

jobs:
  expo-start:
    runs-on: [KU]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Container
      run: |
        docker build . -t admin-web

    - name: Stop Running Container (if exists)
      run: |
        docker stop admin-web || true  # Stop the container if it's running, ignore errors if it doesn't exist

    - name: Remove Previous Container (if exists)
      run: |
        docker rm admin-web || true  # Remove the container if it exists, ignore errors if it doesn't exist

    - name: Run Docker Container
      run: |
        docker run -d --name admin-web -p 19000:8081 admin-webpreview  # Run the new container in detached mode, exposing ports
