name: Run Expo on Test Branch Update

on:
  push:
    branches:
      - test  # Trigger action on pushes to the 'test' branch

jobs:
  expo-start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: |
        npm install  # Install project dependencies

    - name: Run Expo
      run: |
        npx expo install  # Ensure expo-cli is installed if necessary
        nohup npx expo start --non-interactive & # Start Expo in non-interactive mode
